version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=crmifc
      - POSTGRES_USER=crmifc
      - POSTGRES_PASSWORD=12345678