CREATE TABLE IF NOT EXISTS categories (
	id	SERIAL PRIMARY KEY,
	user_id	INT NOT NULL,
	name	VARCHAR (75) UNIQUE NOT NULL,

	/* timestamp */
	created_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
