// Code generated by go-bindata.
// sources:
// migrations/1565894792_users.down.sql
// migrations/1565894792_users.up.sql
// migrations/1569158364_roles.down.sql
// migrations/1569158364_roles.up.sql
// migrations/1570866542_pages.down.sql
// migrations/1570866542_pages.up.sql
// migrations/1571140600_categories.down.sql
// migrations/1571140600_categories.up.sql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __1565894792_usersDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x2d\x4e\x2d\x2a\xb6\xe6\x02\x04\x00\x00\xff\xff\x2c\x02\x3d\xa7\x1c\x00\x00\x00")

func _1565894792_usersDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1565894792_usersDownSql,
		"1565894792_users.down.sql",
	)
}

func _1565894792_usersDownSql() (*asset, error) {
	bytes, err := _1565894792_usersDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1565894792_users.down.sql", size: 28, mode: os.FileMode(420), modTime: time.Unix(1566116474, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1565894792_usersUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x90\x41\x4b\x03\x31\x10\x46\xcf\x93\x5f\x31\xc7\x6e\x29\x54\x04\xf1\xd0\x53\xdc\x4e\x31\x98\x4d\x6b\x36\x91\xf6\x14\x82\x09\x34\xd0\xb5\xcb\x66\x45\x7f\xbe\x74\x71\x6b\x11\xa1\xe0\xf5\xe3\xbd\x61\x78\xa5\x26\x6e\x08\x0d\x7f\x90\x84\x62\x85\x6a\x6d\x90\xb6\xa2\x36\x35\xbe\xe7\xd8\x65\x9c\x30\x48\x01\xa0\x26\x2d\xb8\xc4\x8d\x16\x15\xd7\x3b\x7c\xa2\xdd\x8c\x41\x77\x3c\x44\x97\x02\x0a\x65\x06\x51\x59\x29\x67\x0c\x4e\xe2\x9b\x6f\x22\xbc\x70\x5d\x3e\x72\x8d\x93\xbb\x9b\x02\xad\x12\xcf\x96\x2e\xb9\xd8\xf8\x74\x80\x6b\x54\xeb\x73\xfe\x38\x76\xc1\xed\x7d\xde\xff\xc0\xf7\xb7\xc5\x05\xc5\x60\x3e\xc5\x3e\x35\x31\xf7\xbe\x69\x71\x3a\x67\xf0\xda\x45\xdf\xc7\xe0\x7c\x0f\x46\x54\x54\x1b\x5e\x6d\xce\x06\x2e\x69\xc5\xad\x34\x58\x5a\xad\x49\x19\x77\x46\x4e\xff\xb7\xe1\x3f\x26\x2b\x16\x8c\x7d\xf7\x14\x6a\x49\xdb\xbf\x7a\xba\x31\x8e\x4b\xe1\x13\xd7\x6a\xac\x3c\xce\xc5\xe2\xfa\x89\xa1\xdb\x2f\x7f\xd8\x8a\x05\xb2\xaf\x00\x00\x00\xff\xff\x10\xf2\x3e\xc1\xd1\x01\x00\x00")

func _1565894792_usersUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1565894792_usersUpSql,
		"1565894792_users.up.sql",
	)
}

func _1565894792_usersUpSql() (*asset, error) {
	bytes, err := _1565894792_usersUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1565894792_users.up.sql", size: 465, mode: os.FileMode(420), modTime: time.Unix(1569210888, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1569158364_rolesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\xca\xcf\x49\x2d\xb6\x06\x04\x00\x00\xff\xff\x8c\x8d\x3a\x89\x1b\x00\x00\x00")

func _1569158364_rolesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569158364_rolesDownSql,
		"1569158364_roles.down.sql",
	)
}

func _1569158364_rolesDownSql() (*asset, error) {
	bytes, err := _1569158364_rolesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569158364_roles.down.sql", size: 27, mode: os.FileMode(420), modTime: time.Unix(1569163573, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1569158364_rolesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\xcc\xb1\x4e\x86\x30\x10\xc0\xf1\xf9\xfa\x14\x37\x7e\x1f\x21\xc1\xc5\xc9\xe9\xc4\x23\x36\x96\x8a\xd7\xab\x91\x89\x34\xd2\x81\x44\x94\x40\x7d\x7f\x13\x07\x1e\xe0\xdb\xff\xbf\x7f\x2b\x4c\xca\xa8\xf4\xe8\x18\x6d\x87\xfe\x55\x91\x3f\x6c\xd0\x80\xfb\xcf\x57\x3e\xf0\x62\x60\x99\x01\x02\x8b\x25\x87\x83\xd8\x9e\x64\xc4\x17\x1e\x6b\x03\xdf\x69\xcd\xf0\x4e\xd2\x3e\x93\xe0\xe5\xfe\xee\x8a\xd1\xdb\xb7\xc8\xff\x17\x1f\x9d\xab\x8d\x81\xa6\xc2\xb2\xac\xf9\x28\x69\xdd\xb0\x6a\x0c\x7c\xee\x39\x95\x3c\x4f\xa9\x80\xda\x9e\x83\x52\x3f\x9c\x02\x9f\xb8\xa3\xe8\x14\xdb\x28\xc2\x5e\xa7\x33\xa9\x0d\xfc\x6e\xf3\x2d\xd2\x5c\x1f\xfe\x02\x00\x00\xff\xff\x3b\x99\x38\xe3\xe7\x00\x00\x00")

func _1569158364_rolesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569158364_rolesUpSql,
		"1569158364_roles.up.sql",
	)
}

func _1569158364_rolesUpSql() (*asset, error) {
	bytes, err := _1569158364_rolesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569158364_roles.up.sql", size: 231, mode: os.FileMode(420), modTime: time.Unix(1569216254, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1570866542_pagesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x28\x48\x4c\x4f\x2d\xb6\xe6\x02\x04\x00\x00\xff\xff\x5d\xb2\x15\x0c\x1c\x00\x00\x00")

func _1570866542_pagesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1570866542_pagesDownSql,
		"1570866542_pages.down.sql",
	)
}

func _1570866542_pagesDownSql() (*asset, error) {
	bytes, err := _1570866542_pagesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1570866542_pages.down.sql", size: 28, mode: os.FileMode(420), modTime: time.Unix(1571144203, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1570866542_pagesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\xce\x41\x4b\xc3\x40\x10\x05\xe0\xf3\xcc\xaf\x98\x63\x5b\x0a\x05\xa1\x27\x4f\x63\x9c\xe2\xe2\x26\x96\xc9\x44\xda\x53\x58\xbb\x4b\x59\xb0\x34\x24\xeb\xa1\xff\x5e\xf4\x50\xcc\xd5\xf3\x7b\xdf\xe3\x55\x2a\x6c\x42\xc6\x4f\x5e\xc8\xed\xa8\x79\x33\x92\x83\x6b\xad\xa5\x21\x9c\xd3\x44\x0b\x84\x1c\xa1\x15\x75\xec\x69\xaf\xae\x66\x3d\xd2\xab\x1c\xd7\x08\x5f\x53\x1a\xfb\x1c\xc1\x35\xf6\xeb\x9a\xce\xfb\x35\x42\xc9\xe5\x33\xc1\x3b\x6b\xf5\xc2\x4a\x8b\x87\xed\x76\xf9\x37\xfe\xb8\xc6\x1b\x98\x1c\x66\xe6\x14\x4a\x3a\x5f\xc7\x5b\x9f\x23\xcd\xe7\x10\x36\x2b\x2a\xf9\x92\xa6\x12\x2e\x03\xad\x36\x08\xa7\x31\x85\x92\x62\x1f\x0a\x98\xab\xa5\x35\xae\xf7\x77\x41\xcf\xb2\xe3\xce\x1b\x55\x9d\xaa\x34\xd6\xdf\x2b\x3f\x8f\x87\xf8\x1f\x89\xcb\x47\xc4\xef\x00\x00\x00\xff\xff\xc2\x7c\xd4\xb5\x2a\x01\x00\x00")

func _1570866542_pagesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1570866542_pagesUpSql,
		"1570866542_pages.up.sql",
	)
}

func _1570866542_pagesUpSql() (*asset, error) {
	bytes, err := _1570866542_pagesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1570866542_pages.up.sql", size: 298, mode: os.FileMode(420), modTime: time.Unix(1571144203, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1571140600_categoriesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\x48\x4e\x2c\x49\x4d\xcf\x2f\xca\x4c\x2d\xb6\xe6\x02\x04\x00\x00\xff\xff\xfd\xee\x8d\x6a\x21\x00\x00\x00")

func _1571140600_categoriesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1571140600_categoriesDownSql,
		"1571140600_categories.down.sql",
	)
}

func _1571140600_categoriesDownSql() (*asset, error) {
	bytes, err := _1571140600_categoriesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1571140600_categories.down.sql", size: 33, mode: os.FileMode(420), modTime: time.Unix(1571144203, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __1571140600_categoriesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\xcc\xb1\x4e\xc3\x30\x10\x80\xe1\xf9\xee\x29\x6e\x6c\xab\x48\x65\x61\x62\x3a\xc2\x55\x58\x38\xa6\x9c\xcf\x88\x4e\x91\x95\x58\x28\x43\x20\x4a\xcc\xfb\x23\x31\xe4\x01\xd8\xff\xef\x6f\x55\xd8\x84\x8c\x1f\xbd\x90\xbb\x50\x78\x35\x92\x0f\x17\x2d\xd2\x90\x6b\xf9\xfc\x5e\xa7\xb2\xd1\x01\x61\x1a\x21\x8a\x3a\xf6\x74\x55\xd7\xb1\xde\xe8\x45\x6e\x0d\xc2\x57\x9e\x0b\xbc\xb3\xb6\xcf\xac\x74\xb8\xbf\x3b\x52\x0a\xee\x2d\xc9\xdf\x29\x24\xef\x1b\x44\x38\x9f\xa8\x4e\x73\xd9\x6a\x9e\x17\x3a\x9d\x11\x86\xb5\xe4\x5a\xc6\x3e\x57\x30\xd7\x49\x34\xee\xae\xbb\xa0\x27\xb9\x70\xf2\x46\x6d\x52\x95\x60\xfd\x9e\x34\x08\x3f\xcb\xf8\x1f\x89\xc7\x07\xfc\x0d\x00\x00\xff\xff\xba\x6b\x98\x19\xec\x00\x00\x00")

func _1571140600_categoriesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1571140600_categoriesUpSql,
		"1571140600_categories.up.sql",
	)
}

func _1571140600_categoriesUpSql() (*asset, error) {
	bytes, err := _1571140600_categoriesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1571140600_categories.up.sql", size: 236, mode: os.FileMode(420), modTime: time.Unix(1571163793, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"1565894792_users.down.sql": _1565894792_usersDownSql,
	"1565894792_users.up.sql": _1565894792_usersUpSql,
	"1569158364_roles.down.sql": _1569158364_rolesDownSql,
	"1569158364_roles.up.sql": _1569158364_rolesUpSql,
	"1570866542_pages.down.sql": _1570866542_pagesDownSql,
	"1570866542_pages.up.sql": _1570866542_pagesUpSql,
	"1571140600_categories.down.sql": _1571140600_categoriesDownSql,
	"1571140600_categories.up.sql": _1571140600_categoriesUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"1565894792_users.down.sql": &bintree{_1565894792_usersDownSql, map[string]*bintree{}},
	"1565894792_users.up.sql": &bintree{_1565894792_usersUpSql, map[string]*bintree{}},
	"1569158364_roles.down.sql": &bintree{_1569158364_rolesDownSql, map[string]*bintree{}},
	"1569158364_roles.up.sql": &bintree{_1569158364_rolesUpSql, map[string]*bintree{}},
	"1570866542_pages.down.sql": &bintree{_1570866542_pagesDownSql, map[string]*bintree{}},
	"1570866542_pages.up.sql": &bintree{_1570866542_pagesUpSql, map[string]*bintree{}},
	"1571140600_categories.down.sql": &bintree{_1571140600_categoriesDownSql, map[string]*bintree{}},
	"1571140600_categories.up.sql": &bintree{_1571140600_categoriesUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

